- name: Best Multi-Tier Courses
  subtitle: Education System
  icon: /assets/images/video-logo.png
  
- name: Easy to Use Video Panels
  subtitle: Best LMS System
  icon: /assets/images/video-logo2.png
  
- name: Multi Purpose Dashboard
  subtitle: Online Education
  icon: /assets/images/video-logo3.png
  